import type { GetStaticPaths, GetStaticProps } from "next";
import { Feed, FeedProps } from "../../src/components/Feed";
import {apolloClient, gql} from "../../src/apolloClient";
import { Header, HeaderProps } from '../../src/layout/Header'
import { Footer } from "../../src/components/Footer";
import { FooterMobile } from "../../src/components/FooterMobile";
import Head from 'next/head'


export type PostPageProps = {
  posts: FeedProps["items"];
  pagination: FeedProps["pagination"];
};

export type HomeProps = { 
  userInfo: HeaderProps
}

export type PostPageQuery = {
  page: string
}

export default function PostPage({posts, pagination} : PostPageProps){
  return (
    <>
      <Head>
        <title>Viação Itapemirim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ita.jpg" />
      </Head>
      <header>
          {/* <Header  {... userInfo}/> */}
      </header>
      <Feed items={posts} pagination={pagination}/>

      <footer className="footer">
        <Footer/>
      </footer> 
      <footer className="footer-mobile">
        <FooterMobile />
      </footer>
      <style jsx>{`
        .footer-mobile {
          display:none;
        }

        header {
          padding: 65px;
        }

        .footer {
          position: fixed;
          bottom: 0;
          left: 0;
          width: 100%;
        }

        @media(max-width: 600px){
            .footer {
              display: none;
            }

            .footer-mobile {
              display:block;
              position: fixed;
              bottom: 0;
              left: 0;
              width: 100%;
            }
        }

        @media(max-height: 600px){
            .footer {
                display: none;
            }

            .footer-mobile {
              display:block;
              position: fixed;
              bottom: 0;
              left: 0;
              width: 100%;
            }
        }
      `}</style>
    </>

  )
}

export const getStaticProps : GetStaticProps<PostPageProps, PostPageQuery> = async ({params}) => {
  const result = await apolloClient.query({
    query: gql`
      query{
      itaPosts (pagination:{
        pageSize:4,
        page:${params?.page ?? 1}
      }){
        meta {
          pagination{
            page
            pageSize
            pageCount
          }
        }
      data{
          attributes{
            title
            slug
            image{
              data{
                  attributes{
                    url
                  }
                }
              }
            }
          }
        }
      }
    `
  })

  const posts : FeedProps['items'] = result.data.itaPosts.data.map(({attributes: {title, slug, image: { data: { attributes: { url : image}}}}}:any)=> ({
    image:`https://webservices.jumpingcrab.com${image}`,
    link: `/posts/${slug}`,
    title,
  }));

  const { page:currentPage, pageCount } = result.data.itaPosts.meta.pagination;
  const userInfo = await getUserInfo();
  console.log(userInfo)
  return {
    props: {
      posts,
      pagination: {
        pageCount,
        currentPage,
        hasNextPage: pageCount > currentPage,
        hasPreviousPage: currentPage > 1,
        userInfo
      }
    },
  }

}

export const getStaticPaths : GetStaticPaths<PostPageQuery> = async () => {
  const result = await apolloClient.query({
     query: gql`
      query{
        itaPosts (pagination:{
          pageSize:2,
          page:1
        }){
          meta {
            pagination{
              pageCount
            }
          }
        }
      }   
     `
  })

  const {data: {itaPosts: {meta : {pagination: {pageCount}}}}} = result;
  const postsPage: string[] = Array.from({length: pageCount}, (_, index) => (index +1).toString());
  
  return {
    paths: postsPage.map(page => ({params: {page}})),
    fallback: false
  }

}

async function getUserInfo(): Promise<HeaderProps>{
  const result = await apolloClient.query({
    query: gql`
      query{
        userita {
          data{
            attributes{
              name
              description
              avatar{
                data{
                  attributes{
                    url
                  }
                }
              }
            }
          }
        }
      }
    `
  })
  
  const {name, description, avatar:{ data: { attributes: { url: avatar }}}} = result.data.userita.data.attributes;

  return {name, description, avatar: `https://webservices.jumpingcrab.com${avatar}`}
}