import Head from 'next/head'
import Image from 'next/image'
import { Footer } from '../src/components/Footer'
import { FooterMobile } from '../src/components/FooterMobile'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
      </main>

      <footer className="footer">
        <Footer/>
      </footer> 
      <footer className="footer-mobile">
        <FooterMobile />
      </footer>
      <style jsx>{`
        .footer-mobile {
          display:none;
        }

        .footer {
          position: fixed;
          bottom: 0;
          left: 0;
          width: 100%;
        }

        @media(max-width: 600px){
            .footer {
              display: none;
            }

            .footer-mobile {
              display:block;
              position: fixed;
              bottom: 0;
              left: 0;
              width: 100%;
            }
        }

        @media(max-height: 600px){
            .footer {
                display: none;
            }

            .footer-mobile {
              display:block;
              position: fixed;
              bottom: 0;
              left: 0;
              width: 100%;
            }
        }
      `}</style>
    </div>
  )
}
